### ISSUE TITLE
As a listener, I want to see what show is currently playing along with a live playlist, so I can know what I'm listening to.

### ISSUE THREAD

**Issue by maddievb** [csci312-s21/project-blackberry-binturong#18]

**Comment by ethansaxenian** [comment]
Details to be shown include:
- Title
- DJ(s)
- Playlist

**Comment by maddievb** [comment]
Acceptance tests:
- All the above details are shown (for correct show)
- Playlist is updated when a new song is added
- Show disappears when the show ends/no current show
