### ISSUE TITLE
TO DO: Database

### ISSUE THREAD

**Issue by schester77** [csci312-s21/project-blackberry-binturong#45]
Notes-

- Step one need to store playlists, need playlists to persist on server. DJ creates playlist through PlaylistLogger, user sees it in ShowDetails
- We need to break down each function we expect out of the database
- Endpoints, schema in database, migration, need ids, association with songs and shows
- Not necessarily testable, we have a set of visible acceptance criteria (user stories)
- "As a DJ I want to be able to look back at old show playlists"

**Comment by schester77** [comment]
Data: songs, playlists DJs, Shows

**Comment by schester77** [comment]
Step 1: set up knex
Step 2: create migration
Step 3: seed data (with DJs and Shows)
Step 4: set up functionality

Data type: Playlist 
Functions: Add, Get, Update

Data type: Song
Functions: Add, Get, Delete

Data type: DJs
Functions: just update through data base

Data types: Shows
Functions: just update through data base

Data types: ID for show of the week
Functions: just update through data base

**Comment by madurst22** [comment]
Functions:
DJ functions: Get (DJ from email)

EVERYTHING LEFT:
Add API routes
Use fetch in code
Test fetch in code
Add album art
