### ISSUE TITLE
As a DJ, I want to be able to log my playlists for my show, so listeners can keep track of what I'm playing.

### ISSUE THREAD

**Issue by ethansaxenian** [csci312-s21/project-blackberry-binturong#8]
- Log one song at a time or type them in all at once.
- After entering a song, would like to see if the API fetched the album cover correctly, so we can update it if necessary
- Type in Title, Artist, and Album
- Can delete or update a song

**Comment by maddievb** [comment]
Acceptance tests:
- When you type into the text input and enter the next song, it will render all of that text on the page
- Cannot enter a song until all of the fields are completed
- When we delete a song, it disappears from the page
- When we update a song, the information gets updated

**Comment by ethansaxenian** [comment]
This component will be called `PlaylistLogger`
